# Generated by Django 3.2 on 2021-04-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhlfa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='number',
            new_name='apiID',
        ),
    ]
