# Generated by Django 3.2 on 2021-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlfa_app', '0004_auto_20210421_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nhlTeam',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
