# Generated by Django 3.2 on 2021-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlfa_app', '0005_player_nhlteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nhlTeam',
            field=models.CharField(choices=[('NJD', 'New Jersey Devils'), ('NYI', 'New York Islanders'), ('NYR', 'New York Rangers'), ('PF', 'Philadelphia Flyers'), ('PP', 'Pittsburgh Penguins'), ('BB', 'Boston Bruins'), ('BS', 'Buffalo Sabres'), ('MC', 'Montréal Canadiens'), ('OC', 'Ottawa Senators'), ('TMF', 'Toronto Maple Leafs'), ('CH', 'Carolina Hurricanes'), ('FP', 'Florida Panthers'), ('TBL', 'Tampa Bay Lightning'), ('WC', 'Washington Capitals'), ('CB', 'Chicago Blackhawks'), ('DRW', 'Detroit Red Wings'), ('NP', 'Nashville Predators'), ('SLB', 'St. Louis Blues'), ('CF', 'Calgary Flames'), ('CA', 'Colorado Avalanche'), ('EO', 'Edmonton Oilers'), ('VC', 'Vancouver Canucks'), ('AD', 'Anaheim Ducks'), ('DS', 'Dallas Stars'), ('LAK', 'Los Angeles Kings'), ('SJS', 'San Jose Sharks'), ('CBJ', 'Columbus Blue Jackets'), ('MW', 'Minnesota Wild'), ('WJ', 'Winnipeg Jets'), ('AC', 'Arizona Coyotes'), ('VGK', 'Vegas Golden Knights')], max_length=255, null=True),
        ),
    ]
