# Generated by Django 3.2 on 2021-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlfa_app', '0006_alter_player_nhlteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nhlTeam',
            field=models.CharField(choices=[('New Jersey Devils', 'New Jersey Devils'), ('New York Islanders', 'New York Islanders'), ('New York Rangers', 'New York Rangers'), ('Philadelphia Flyers', 'Philadelphia Flyers'), ('Pittsburgh Penguins', 'Pittsburgh Penguins'), ('Boston Bruins', 'Boston Bruins'), ('Buffalo Sabres', 'Buffalo Sabres'), ('Montréal Canadiens', 'Montréal Canadiens'), ('Ottawa Senators', 'Ottawa Senators'), ('Toronto Maple Leafs', 'Toronto Maple Leafs'), ('Carolina Hurricanes', 'Carolina Hurricanes'), ('Florida Panthers', 'Florida Panthers'), ('Tampa Bay Lightning', 'Tampa Bay Lightning'), ('Washington Capitals', 'Washington Capitals'), ('Chicago Blackhawks', 'Chicago Blackhawks'), ('Detroit Red Wings', 'Detroit Red Wings'), ('Nashville Predators', 'Nashville Predators'), ('St. Louis Blues', 'St. Louis Blues'), ('Calgary Flames', 'Calgary Flames'), ('Colorado Avalanche', 'Colorado Avalanche'), ('Edmonton Oilers', 'Edmonton Oilers'), ('Vancouver Canucks', 'Vancouver Canucks'), ('Anaheim Ducks', 'Anaheim Ducks'), ('Dallas Stars', 'Dallas Stars'), ('Los Angeles Kings', 'Los Angeles Kings'), ('San Jose Sharks', 'San Jose Sharks'), ('Columbus Blue Jackets', 'Columbus Blue Jackets'), ('Minnesota Wild', 'Minnesota Wild'), ('Winnipeg Jets', 'Winnipeg Jets'), ('Arizona Coyotes', 'Arizona Coyotes'), ('Vegas Golden Knights', 'Vegas Golden Knights')], max_length=255, null=True),
        ),
    ]
